config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :analysis, only: [:index]
  resources :results, only: [:index]
  resources :costs, only: [:index]
  resources :fa_performances, only: [:index]
  resources :fa_allocations, only: [:index]
  resources :non_staff_costs
  resources :reporting_periods do
    resources :reports, only: [:new, :create]
    resources :bulk_import, only: [:new, :create]
    get "income", on: :collection
    get "reports", on: :member
    get "announce", on: :member
  end
  resources :invoices
  patch "reporting_periods/:id/update_state", to: "reporting_periods#update_state", as: :reporting_period_update_state
  get "slack/:reporting_id/:id", to: "slack#send_notification", as: :slack_send_notification

  resources :reports, only: [:edit, :update, :destroy]
  resources :users do
    get "reports", on: :member
  end
  resources :projects do
    member do
      get "project_links", to: "project_links#edit"
      patch "project_links", to: "project_links#update"
    end
  end
  resources :contracts do
    resources :progress_reports, only: [:new, :create, :edit, :update]
    member do
      get "reports"
      get "team"
      get "costs"
    end
  end
  get "my-report", to: "reports#edit"
  resources :roles
  resources :teams do
    get "members", on: :member
  end
  resources :rates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_nav.html.erb
<% if current_user %>
  <ul class="vertical-nav-menu">
    <% if Rails.env.development? %>
      <li class="app-sidebar__heading">Development</li>
      <li><%= switch_user_select %></li>
    <% end %>
    <li class="app-sidebar__heading">Menu</li>
    <li class="<%= "mm-active" if ['reporting_periods', 'results', 'invoices', 'reporting_periods', 'results', 'costs', 'fa_performances', 'fa_allocations'].include?(controller_name) %>">
      <a href="#">
        <i class="metismenu-icon pe-7s-piggy"></i>
        Finances
        <i class="metismenu-state-icon pe-7s-angle-down care-left"></i>
      </a>
      <ul>
        <li>
          <%= link_to :reporting_periods, class: (controller_name == 'reporting_periods' && action_name == 'index' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            Reporting Periods
          <% end %>
        </li>
        <li>
          <%= link_to :invoices, class: (controller_name == 'invoices' && action_name == 'index' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            Invoices
          <% end %>
        </li>
        <% if current_user.admin? %>
          <li>
            <%= link_to income_reporting_periods_path, class: (controller_name == 'reporting_periods' && action_name == 'income' && 'mm-active') do %>
              <i class="metismenu-icon"></i>
              Income (6 months)
            <% end %>
          </li>
          <li>
            <%= link_to results_path, class: (controller_name == 'results' && action_name == 'index' && 'mm-active') do %>
              <i class="metismenu-icon"></i>
              Monthly breakdown
            <% end %>
          </li>
          <li>
            <%= link_to costs_path, class: (controller_name == 'costs' && action_name == 'index' && 'mm-active') do %>
              <i class="metismenu-icon"></i>
              Monthly costs
            <% end %>
          </li>
          <li>
            <%= link_to fa_performances_path, class: (controller_name == 'fa_performances' && action_name == 'index' && 'mm-active') do %>
              <i class="metismenu-icon"></i>
              FA performance
            <% end %>
          </li>
          <li>
            <%= link_to fa_allocations_path, class: (controller_name == 'fa_allocations' && action_name == 'index' && 'mm-active') do %>
              <i class="metismenu-icon"></i>
              FA allocation
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
    <li class="<%= "mm-active" if ['contracts', 'projects', 'non_staff_costs'].include?(controller_name) %>">
      <a href="#">
        <i class="metismenu-icon pe-7s-portfolio"></i>
        Contracts & Projects
        <i class="metismenu-state-icon pe-7s-angle-down care-left"></i>
      </a>
      <ul>
        <li>
          <%= link_to :contracts, class: (controller_name == 'contracts' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            Contracts
          <% end %>
        </li>
        <li>
          <%= link_to :projects, class: (controller_name == 'projects' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            Projects
          <% end %>
        </li>
        <li>
          <%= link_to :non_staff_costs, class: (controller_name == 'non_staff_costs' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            Non Staff Costs
          <% end %>
        </li>
      </ul>
    </li>
    <li class="<%= "mm-active" if ['users', 'teams', 'roles', 'rates'].include?(controller_name) %>">
      <a href="#">
        <i class="metismenu-icon pe-7s-users"></i>
        People
        <i class="metismenu-state-icon pe-7s-angle-down care-left"></i>
      </a>
      <ul>
        <li>
          <%= link_to :users, class: (controller_name == 'users' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            People
          <% end %>
        </li>
        <li>
          <%= link_to :roles, class: (controller_name == 'roles' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            Functional Areas
          <% end %>
        </li>
        <li>
          <%= link_to :rates, class: (controller_name == 'rates' && 'mm-active') do %>
            <i class="metismenu-icon"></i>
            Rates
          <% end %>
        </li>
      </ul>
    </li>
    <li class="app-sidebar__heading">Useful Links</li>
    <li>
      <a href="https://drive.google.com/drive/folders/1ycjuPMQYsD1rke-edupftI6GCHLlpWWS" target='_blank' rel="nofollow noopener">
        <i class="metismenu-icon pe-7s-folder"></i>
        #Projects @ GDrive
      </a>
    </li>
    <li>
      <a href="https://vizzuality.github.io/playbook/" target='_blank' rel="nofollow noopener">
        <i class="metismenu-icon pe-7s-joy"></i>
        Playbook
      </a>
    </li>
    <li>
      <a href="https://vizzuality.bamboohr.com/" target='_blank' rel="nofollow noopener">
        <i class="metismenu-icon pe-7s-id"></i>
        BambooHR
      </a>
    </li>
    <li>
      <a href="https://vizzuality.blogin.co/" target='_blank' rel="nofollow noopener">
        <i class="metismenu-icon pe-7s-note"></i>
        Blogin
      </a>
    </li>
  </ul>
<% end %>

app/views/shared/_user_nav.html.erb
<div class="app-header__content">
  <div class="app-header-left">
    <ul class="header-megamenu nav">
      <li class="dropdown nav-item">
        <a aria-haspopup="true" data-toggle="dropdown" class="nav-link" aria-expanded="false">
          <i class="nav-link-icon pe-7s-note2"></i>
          Quick Access
          <i class="fa fa-angle-down ml-2 opacity-5"></i>
        </a>
        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu-rounded dropdown-menu-lg rm-pointers dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 37px, 0px);">
          <% @quick_contracts.each do |contract| %>
            <%= link_to contract, class: 'dropdown-item', tabindex: '0' do %>
              <i class="dropdown-icon lnr-file-empty"> </i><%= contract.name %>
            <% end %>
          <% end %>
          <% if current_user %>
            <div tabindex="-1" class="dropdown-divider"></div>

            <% if current_user.role %>
              <%= link_to current_user.role, class: 'dropdown-item', tabindex: '0' do %>
                <i class="dropdown-icon lnr-paperclip"> </i><%= "#{current_user.role.name} Page" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
  <div class="app-header-right">
    <% if current_user && current_user.current_report %>
      <div class="header-dots">
        <%= link_to 'Latest Report', '/my-report', class: 'btn btn-outline-success my-2 my-sm-0' %>
      </div>
    <% end %>
    <div class="header-btn-lg pr-0">
      <div class="widget-content p-0">
        <div class="widget-content-wrapper">
          <% if current_user %>
            <div class="widget-content-left">
              <div class="btn-group">
                <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                  <%= image_tag(current_user.gravatar_url(42), width: 42, alt: current_user.name, class: 'rounded-circle') %>
                  <i class="fa fa-angle-down ml-2 opacity-8"></i>
                </a>
                <div tabindex="-1" role="menu" aria-hidden="true" class="rm-pointers dropdown-menu-lg dropdown-menu dropdown-menu-right">
                  <div class="dropdown-menu-header">
                    <div class="dropdown-menu-header-inner bg-info">
                      <div class="menu-header-image opacity-2" style="background-image: url('assets/images/dropdown-header/city3.jpg');"></div>
                      <div class="menu-header-content text-left">
                        <div class="widget-content p-0">
                          <div class="widget-content-wrapper">
                            <div class="widget-content-left mr-3">
                              <%= image_tag(current_user.gravatar_url(42), width: 42, alt: current_user.name, class: 'rounded-circle') %>
                            </div>
                            <div class="widget-content-left">
                              <div class="widget-heading">
                                <%= current_user.name %>
                              </div>
                              <div class="widget-subheading opacity-8">
                                A short profile description
                              </div>
                            </div>
                            <div class="widget-content-right mr-2">
                              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn-pill btn-shadow btn-shine btn btn-focus" %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="scroll-area-xs" style="height: 150px;">
                    <div class="scrollbar-container ps">
                      <ul class="nav flex-column">
                        <li class="nav-item-header nav-item">My Account
                        </li>
                        <li class="nav-item">
                          <%= link_to "Profile", current_user, class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                          <%= link_to "My Reports", reports_user_path(current_user), class: "nav-link" %>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="widget-content-left ml-3 header-user-info">
              <div class="widget-heading">
                <%= current_user.name %>
              </div>
              <div class="widget-subheading">
                <%= current_user.role&.name %>
              </div>
            </div>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>