config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :analysis, only: [:index]
  resources :results, only: [:index]
  resources :costs, only: [:index]
  resources :fa_performances, only: [:index]
  resources :fa_allocations, only: [:index]
  resources :non_staff_costs
  resources :reporting_periods do
    resources :reports, only: [:new, :create]
    resources :bulk_import, only: [:new, :create]
    get "income", on: :collection
    get "reports", on: :member
    get "announce", on: :member
  end
  resources :invoices
  patch "reporting_periods/:id/update_state", to: "reporting_periods#update_state", as: :reporting_period_update_state
  get "slack/:reporting_id/:id", to: "slack#send_notification", as: :slack_send_notification

  resources :reports, only: [:edit, :update, :destroy]
  resources :users do
    get "reports", on: :member
  end
  resources :projects do
    member do
      get "project_links", to: "project_links#edit"
      patch "project_links", to: "project_links#update"
    end
  end
  resources :contracts do
    resources :progress_reports, only: [:new, :create, :edit, :update]
    member do
      get "reports"
      get "team"
      get "costs"
    end
  end
  get "my-report", to: "reports#edit"
  resources :roles
  resources :teams do
    get "members", on: :member
  end
  resources :rates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :bigint           not null, primary key
#  is_billable :boolean          default(TRUE)
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  team_id     :bigint
#
# Indexes
#
#  index_projects_on_name     (name) UNIQUE
#  index_projects_on_team_id  (team_id)
#
# Foreign Keys
#
#  fk_rails_...  (team_id => teams.id)
#

class Project < ApplicationRecord
  belongs_to :team, optional: true
  has_many :contracts, dependent: :restrict_with_error

  has_many :full_reports, through: :contracts
  has_many :report_parts, through: :contracts
  has_many :reports, through: :report_parts
  has_many :users, through: :reports
  has_many :reporting_periods, through: :reports

  has_many :project_links, dependent: :restrict_with_error
  accepts_nested_attributes_for :project_links,
    allow_destroy: true,
    reject_if: proc { |attributes| attributes["title"].blank? || attributes["url"].blank? }

  validates :name, uniqueness: true, presence: true

  def budget
    contracts.try(:sum, :budget)
  end

  def costs
    contracts.map(&:total_burn).compact.reduce(:+)
  end

  def burn_percentage
    (costs / budget * 100).round(2)
  end

  def self.search query
    return all unless query

    where("name ilike ?", "%#{query}%")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(is_billable: :desc, name: :asc)
      .includes(:team, contracts: [:full_reports])
      .search(params[:search]).page(params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @teams = Team.order(:name)
    @project.contracts.build
    @contract_states = Contract.aasm.states.map(&:name).prepend(:all)
  end

  # GET /projects/1/edit
  def edit
    @teams = Team.order(:name)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to :projects, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html do
          @teams = Team.order(:name)
          render :new
        end
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html do
          @teams = Team.order(:name)
          render :edit
        end
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :team_id, :is_billable)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <%= form_with(model: project, local: true) do |form| %>
          <% if project.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

              <ul>
                <% project.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="position-relative row form-group">
            <%= form.label :name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= form.text_field :name, class: 'form-control' %>
            </div>
          </div>

          <div class="position-relative row form-group">
            <%= form.label :is_billable, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= form.check_box :is_billable, class: 'form-control' %>
            </div>
          </div>

          <div class="position-relative row form-group">
            <%= form.label :team_id, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= form.collection_select :team_id, @teams, :id, :name, { include_blank: true }, class: 'form-control' %>
            </div>
          </div>

          <div class="position-relative row form-group">
            <div class="col-sm-10 offset-sm-2">
              <%= form.submit "Submit", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing Project" %>
<% content_for :actions,
  link_to('Show', @project, class: 'btn btn-sm btn-outline-primary').concat(
    link_to('Back', projects_path, class: 'btn btn-sm btn-outline-secondary'))
%>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<% content_for :title, "Projects" %>
<% if can? :create, Project %>
  <% content_for :actions,
    link_to('New Project', new_project_path, class: 'btn btn-sm btn-outline-primary') %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <%= form_with(url: 'projects#index', method: :get, local: true, class: 'form-inline') do |form| %>
      <%= form.label :search, 'Search', class: 'sr-only' %>
      <%= text_field_tag :search, params[:search], class: 'form-control col-sm-12 mb-2',
        placeholder: 'Search projects', onblur: 'this.form.submit();', onenter: 'this.form.submit();' %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <div class="table-responsive">
          <%= page_entries_info @projects %>
          <table class="table table-lg table-hover table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Contracts #</th>
                <th>Total Budget</th>
                <th>Total Costs</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              <% @projects.each do |project| %>
                <tr>
                  <td>
                    <%= billable_tag(project) %>
                    <%= link_to project.name, project %>
                  </td>
                  <td><%= project.contracts.size %></td>
                  <td><%= number_to_currency(project.budget) %></td>
                  <td><%= number_to_currency(project.costs) %></td>
                  <td>
                    <%= link_to 'Show', project %>
                    <% if can? :manage, project %>
                      <%= link_to 'Edit', edit_project_path(project) %>
                      <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @projects %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New Project" %>
<% content_for :actions,
  link_to('Back', projects_path, class: 'btn btn-sm btn-outline-secondary') %>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<% content_for :title do %>
  <%= "Project - #{@project.name}" %>
  <%= billable_tag(@project) %>
<% end %>
<% content_for :actions do
  actions = link_to('Manage Links', project_links_project_path(@project), class: 'btn btn-sm btn-outline-secondary')
    .concat(link_to('Back', projects_path, class: 'btn btn-sm btn-outline-secondary'))
  if can? :edit, @project
    actions = actions.concat(link_to('Edit', edit_project_path(@project), class: 'btn btn-sm btn-outline-primary'))
  end
  actions
end %>

<div class="row">
  <div class="col-md-3">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <h5 class="card-title">Project Links</h5>
        <ul>
          <% link_type = nil %>
          <% @project.project_links.order(:link_type, :title).each do |pl| %>
            <%= content_tag(:strong, pl.link_type.humanize) if !link_type || link_type != pl.link_type %>
            <% link_type = pl.link_type %>
            <li><%= link_to pl.title, pl.url, target: '_blank', rel: 'noopener nofollow' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <h5 class="card-title">Contracts</h5>
        <div class="table-responsive">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Budget</th>
                <th>Costs</th>
                <th>Days spent</th>
                <th>Start date</th>
                <th>End date</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @project.contracts.order("contracts.end_date desc").each do |contract| %>
                <tr>
                  <td><%= contract.code %></td>
                  <td><%= link_to contract.name, contract %> (<%= contract.aasm_state.humanize %>)</td>
                  <td>
                    <%= number_to_currency(contract.budget) %>
                  </td>
                  <td>
                    <%= number_to_currency(contract.full_reports.sum(:cost)) %>
                  </td>
                  <td><%= contract.full_reports.sum(:days) %></td>
                  <td><%= contract.start_date %></td>
                  <td><%= contract.end_date %></td>
                  <td>
                    <% if can? :edit, contract %>
                      |
                      <%= link_to 'Edit', edit_contract_path(contract) %>
                    <% end %>
                    <% if can? :manage, contract %>
                      |
                      <%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>