config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :analysis, only: [:index]
  resources :results, only: [:index]
  resources :costs, only: [:index]
  resources :fa_performances, only: [:index]
  resources :fa_allocations, only: [:index]
  resources :non_staff_costs
  resources :reporting_periods do
    resources :reports, only: [:new, :create]
    resources :bulk_import, only: [:new, :create]
    get "income", on: :collection
    get "reports", on: :member
    get "announce", on: :member
  end
  resources :invoices
  patch "reporting_periods/:id/update_state", to: "reporting_periods#update_state", as: :reporting_period_update_state
  get "slack/:reporting_id/:id", to: "slack#send_notification", as: :slack_send_notification

  resources :reports, only: [:edit, :update, :destroy]
  resources :users do
    get "reports", on: :member
  end
  resources :projects do
    member do
      get "project_links", to: "project_links#edit"
      patch "project_links", to: "project_links#update"
    end
  end
  resources :contracts do
    resources :progress_reports, only: [:new, :create, :edit, :update]
    member do
      get "reports"
      get "team"
      get "costs"
    end
  end
  get "my-report", to: "reports#edit"
  resources :roles
  resources :teams do
    get "members", on: :member
  end
  resources :rates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id                  :bigint           not null, primary key
#  estimated           :boolean          default(FALSE)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  reporting_period_id :bigint           not null
#  team_id             :integer
#  user_id             :bigint           not null
#
# Indexes
#
#  index_reports_on_reporting_period_id  (reporting_period_id)
#  index_reports_on_team_id              (team_id)
#  index_reports_on_user_id              (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (reporting_period_id => reporting_periods.id)
#  fk_rails_...  (team_id => teams.id)
#  fk_rails_...  (user_id => users.id)
#

class Report < ApplicationRecord
  belongs_to :user
  belongs_to :team, optional: true
  belongs_to :reporting_period
  has_many :report_parts, dependent: :destroy
  accepts_nested_attributes_for :report_parts, allow_destroy: true

  has_many :contracts, through: :report_parts

  def rate
    reporting_period.base_rate
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :set_resources, only: [:edit]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @reporting_periods = ReportingPeriod.order(:date)
    @users = User.order(:name)
    @contracts = Contract.with_status([:live])
      .order(:name)
    @roles = Role.order(:name)
    @teams = Team.order(:name)

    @report = if params[:reporting_period_id]
      ReportingPeriod.find(params[:reporting_period_id]).reports.new
    else
      Report.new
    end
    @report.report_parts.build
  end

  # GET /reports/1/edit
  def edit
    redirect_to user_url(current_user), notice: "No Report available to edit" and return unless @report

    authorize! :edit, @report
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to reporting_periods_url, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      was_estimate = @report.estimated
      begin
        @report.update(report_params)
      rescue ActiveRecord::RecordNotUnique
        @report.errors.add(:base, "Validation failed, please ensure you are not reporting duplicate contracts.")
      end

      if @report.errors.empty?
        format.html { redirect_to update_redirect_path, notice: notice_after_update(was_estimate) }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html do
          set_resources
          render :edit
        end
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @reporting_period = @report.reporting_period
    @report.destroy
    respond_to do |format|
      format.html { redirect_to @reporting_period, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = params[:id].present? ? Report.find(params[:id]) : current_user.current_report
  end

  def set_resources
    @reporting_periods = ReportingPeriod.order(:date)
    @users = User.order(:name)
    # if editing an old report, let's not constraint the available contracts to report on
    @contracts = if !@report || @report.reporting_period.aasm_state != "active"
      Contract.order(:name).includes(:project)
    else
      Contract.with_status([:live])
        .or(Contract.with_status([:live]).where(id: @report.report_parts.pluck(:contract_id)))
        .order(:name).includes(:project)
    end
    @roles = Role.order(:name)
    @teams = Team.order(:name)
    # byebug
  end

  def notice_after_update was_estimate
    if !@report.estimated && was_estimate
      "Thank you for submitting this month's report!"
    else
      "Report successfully updated, thank you."
    end
  end

  def update_redirect_path
    if @report.user == current_user
      @report.user
    else
      @report.reporting_period
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(:user_id, :team_id, :reporting_period_id, :estimated,
      report_parts_attributes: [:id, :percentage,
        :contract_id, :role_id,
        :_destroy])
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <%= form_with(model: report, local: true) do |form| %>
          <% if report.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

              <ul>
                <% report.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="alert alert-success">
            1 day equals 5%.
            5 days equals 25%.
            Part time employees don't need to adjust, as this is done automatically.
          </div>
          <% if report.user == current_user %>
            <%= form.hidden_field :estimated, value: false %>
          <% else %>
            <div class="form-group">
              <%= form.label :estimated %>
              <%= form.check_box :estimated, {}, class: "form-control" %>
            </div>
          <% end %>
          <% if report.new_record? %>
            <div class="form-group">
              <%= form.label :reporting_period_id %>
              <%= form.collection_select :reporting_period_id, @reporting_periods, :id,
                :display_name, {}, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :user_id %>
              <%= form.collection_select :user_id, @users, :id,
                :name, {selected: form.object.user_id || current_user.id}, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :team_id %>
              <%= form.collection_select :team_id, @teams, :id,
                :name, {selected: form.object.team_id || current_user.team_id}, class: 'form-control' %>
            </div>
          <% end %>

          <div data-controller="nested-list">
            <template>
              <%= form.fields_for :report_parts, ReportPart.new, child_index: 'NEW_RECORD' do |builder| %>
                <%= render "report_part_fields", form: builder %>
              <% end %>
            </template>
            <table class="table">
              <thead>
                <tr>
                  <th>Project</th>
                  <th>Functional Area</th>
                  <th>Percentage</th>
                  <th></th>
                </tr>
              </thead>
              <tbody data-controller="report-percentages">
                <%= form.fields_for :report_parts do |builder| %>
                  <%= render 'report_part_fields', form: builder %>
                <% end %>
                <tr class="nested-list__actions" data-target="nested-list.links">
                  <th colspan="2">
                    <%= button_tag "Add Line", type: 'button',
                      class: 'btn btn-secondary',
                      data: { action: "click->nested-list#addRecord", target: "total-percentages.source" } %>
                    <span class="float-right pt-2">Total</span>
                  </th>
                  <th>
                    <div class="input-group">
                      <input type="text" data-target="report-percentages.display" disabled value="<%= report.report_parts.sum(:percentage) %>" class="form-control">
                      <div class="input-group-append">
                        <div class="input-group-text">%</div>
                      </div>
                    </div>
                  </th>
                  <th>
                    <%= form.submit "Submit", class: "btn btn-primary" %>
                  </th>
                </tr>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reports/_non_project_reporting.html.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="reportsInfoModal" aria-hidden="true" style="display: none;" id="reportsInfoModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="progressModalTitle">How to report</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
       <h5>Contracts</h5>
        <p>A contract represents what we call internally a project, usually where people with an engineering, design, research, science, data, or project management role will report most of their time. There may be exceptions, depending on unique project requirements or certain business times. This applies regardless of whether a task exceeds its expected duration if it necessitates learning something new, onboarding a new team member to a project or any other particular scenario. The key is that our efforts are enhancing the project's value directly.</p>

        <h5>Marketing & Business Development (MKT & BD)</h5>
        <p>All marketing and business development tasks. This can be anything from generating new project leads, writing proposals for potential clients, attending new scope of work meetings, or participating in conferences and networking events.</p>

        <h5>Communications (Comms)</h5>
        <p>Activities related to creating and managing both internal and external communication. This includes writing and editing blog posts, creating and scheduling social media posts, updating our websites, and any other content creation for Vizzuality's communication channels.</p>
        <p>Note: Some communication activities are included in the clients' contracts. In that case, those tasks should be reported under the respective projects.</p>

        <h5>Operations</h5>
        <p>All activities essential to the functioning of Vizzuality that cannot be directly linked to a specific project, MKT&BD, Comms or training. This includes functional area meetings, all-hands meetings, and hiring activities. Cross-functional strategic meetings and functional area leadership are considered operational tasks. Lightning talks that deal with efficiency or present new processes and workflows should also be tagged as operations. Technical lightning talks about new technologies or for sharing knowledge on a certain topic should be reported under mentoring (see point 6.)</p>
        <p>Note: It is expected that operations take up 5-10% of junior and mid-level profiles reporting, whereas it can be more significant in senior positions. Ideally, operations should not exceed 20% of a person’s time (except for specific profiles). During overcapacity periods, idle time should be monitored, and for that reason, tagged independently from operations (see point 8.).</p>

        <h5>Growth Plan</h5>
        <p>This category is reserved for learning activities aimed at professional development. It may also include activities like attending a lightning talk about a specific technology, or learning a new technique. Time dedicated to attending a course should be registered here.</p>
        <p>We believe that learning and the growth plan are crucial at our company; hence, we think that these activities cannot be reactive and driven by a lack of basic knowledge to address project problems. On the other hand, if a project brings some technical challenges, new technologies, or techniques, these have been considered when writing the proposal, so, this time must be reported to that specific contract.</p>
        <p>Note: New staff undergoing general company onboarding should report their onboarding time in this category. Please note that, onboarding a new team member to a project is project related and should be reported under its respective contract. Exceptions can be made for project onboardings that are part of the general company onboarding. However, all these exceptional and specific cases should have a team agreement.</p>

        <h5>Mentoring</h5>
        <p>Mentoring is the time we spend doing company general onboarding, helping others with their growth plan, or solving doubts or advice on projects. These must be reported to mentoring, not to operations. Teaching other team members about specific technical issues or preparing and giving a talk internally should be reported under mentoring.</p>
        <p>Note: To ensure clarity, if your contributions are enhancing the project in a significant way, they should be logged under the project's contract. For instance, if you're coding, designing, or processing data to introduce a discernible feature or benefit to the project, such activities must be reported to the project's contract.</p>

        <h5>Vacation/Absence</h5>
        <p>Vacation time or justified absences, such as parental or medical leaves. National or regional bank holidays should NOT be reported. Absences must also be logged in Bamboo.</p>

        <h5>Idle</h5>
        <p>Time that is not actively engaged in productive work. This time cannot be associated with a specific project, nor directly related to company activities or operations. During regular operation times, we aim to keep this at 0%. For that, it is key to turn any idle time into productive time. This could mean going the extra mile on ongoing projects, helping other team members or other FAs, or working on internal projects.</p>
        <p>Note: If you find yourself with idle time, talk to your FA to identify needs and initiatives where you can contribute. Be proactive and suggest some ideas too. For FAs, as a rule of thumb, project work should be assigned to junior and mid profiles, freeing senior members to more strategic tasks focusing on efficiency and innovation. Balancing the workload across all members of the same FA is also something to consider.</p>
        <p class="alert alert-info">
          If you have any questions about reporting ask the team involved (eg. Doubts on operations reporting ask Laura/David; doubts on projects ask PMs; doubts on marketing ask BD; etc)
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/reports/_report_part_fields.html.erb
<% if form.object.contract && form.object.contract.aasm_state == "live" || form.object.new_record? %>
  <% is_new_record = form.object.new_record? %>
  <%= content_tag :tr,
    class: 'report-parts-fields nested-fields',
    data: { controller: 'report-part', new_record: is_new_record } do %>
    <td>
      <%= form.collection_select :contract_id, @contracts, :id,
        :full_name, {}, class: 'form-control' %>
    </td>
    <td>
      <%= form.collection_select :role_id, @roles, :id,
        :name, {selected: form.object.role_id || @report.user.role_id}, class: 'form-control' %>
    </td>

    <td>
      <div class="input-group">
        <%= form.text_field :percentage, class: 'form-control',
            data: { action: 'change->report-percentages#recalc', target: 'report-percentages.source' }%>
        <div class="input-group-append">
          <div class="input-group-text">%</div>
        </div>
      </div>
    </td>
    <td>
      <%= button_tag 'Remove', type: 'button',
        class: 'btn btn-danger',
        data: { action: 'click->nested-list#removeRecord click->report-percentages#recalc' } %>
    </td>

    <%= form.hidden_field :_destroy %>
  <% end %>
<% end %>

app/views/reports/edit.html.erb
<% content_for :title, "Editing Report - #{@report.reporting_period.display_name}" %>
<% content_for :actions do
content_tag(:button, "How to report",
            data: { toggle: 'modal', target: '#reportsInfoModal' },
            class: 'btn btn-sm mr-3 btn-primary')
      .concat(link_to('Back', current_user, class: 'btn btn-sm btn-outline-primary'))
  end
%>
<% content_for :modals, render('non_project_reporting') %>

<%= render 'form', report: @report %>

app/views/reports/index.html.erb
<% content_for :title, "Reports" %>
<% content_for :actions, link_to('New Report', new_report_path) %>

<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th>User</th>
              <th>Functional Area</th>
              <th>Reporting period</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @reports.each do |report| %>
              <tr>
                <td><%= report.user_id %></td>
                <td><%= report.role_id %></td>
                <td><%= report.reporting_period_id %></td>
                <td><%= link_to 'Show', report %></td>
                <td><%= link_to 'Edit', edit_report_path(report) %></td>
                <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<% content_for :title, "New Report" %>
<% content_for :actions do
  link_to 'Back', reporting_periods_path,
    class: 'btn btn-sm btn-outline-primary'
  end
%>

<%= render 'form', report: @report %>

app/views/reports/show.html.erb
<p>
  <strong>User:</strong>
  <%= @report.user_id %>
</p>

<p>
  <strong>Functional Area:</strong>
  <%= @report.role_id %>
</p>

<p>
  <strong>Reporting period:</strong>
  <%= @report.reporting_period_id %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>