config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :analysis, only: [:index]
  resources :results, only: [:index]
  resources :costs, only: [:index]
  resources :fa_performances, only: [:index]
  resources :fa_allocations, only: [:index]
  resources :non_staff_costs
  resources :reporting_periods do
    resources :reports, only: [:new, :create]
    resources :bulk_import, only: [:new, :create]
    get "income", on: :collection
    get "reports", on: :member
    get "announce", on: :member
  end
  resources :invoices
  patch "reporting_periods/:id/update_state", to: "reporting_periods#update_state", as: :reporting_period_update_state
  get "slack/:reporting_id/:id", to: "slack#send_notification", as: :slack_send_notification

  resources :reports, only: [:edit, :update, :destroy]
  resources :users do
    get "reports", on: :member
  end
  resources :projects do
    member do
      get "project_links", to: "project_links#edit"
      patch "project_links", to: "project_links#update"
    end
  end
  resources :contracts do
    resources :progress_reports, only: [:new, :create, :edit, :update]
    member do
      get "reports"
      get "team"
      get "costs"
    end
  end
  get "my-report", to: "reports#edit"
  resources :roles
  resources :teams do
    get "members", on: :member
  end
  resources :rates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reporting_period.rb
# == Schema Information
#
# Table name: reporting_periods
#
#  id         :bigint           not null, primary key
#  aasm_state :string
#  base_rate  :float            default(175.0)
#  date       :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_reporting_periods_on_date  (date) UNIQUE
#
require "csv"

class ReportingPeriod < ApplicationRecord
  paginates_per 10

  include AASM
  include HasStateMachine

  aasm do
    state :unstarted, initial: true
    state :active, before_enter: proc { ReportingPeriod.deactivate_active_reporting! }
    state :finished
    event :start do
    end
    event :activate do
      transitions from: :unstarted, to: :active
    end
    event :terminate do
      transitions from: :active, to: :finished
    end
    event :reactivate do
      transitions from: :finished, to: :active
    end
  end

  def self.deactivate_active_reporting!
    ReportingPeriod.where(aasm_state: "active").find_each(&:terminate!)
  end

  has_many :reports, dependent: :destroy
  has_many :report_parts, through: :reports
  has_many :contracts, through: :report_parts
  has_many :users, through: :reports
  has_many :full_reports, dependent: :restrict_with_error
  has_many :non_staff_costs, dependent: :destroy

  validates :date, uniqueness: true

  def self.active_period
    ReportingPeriod.find_by(aasm_state: "active")
  end

  def display_name
    date.strftime("%B %Y")
  end

  def total_contracts_reported
    full_reports.select(:contract_id).distinct.count
  end

  def total_time_reported
    full_reports.sum(:days)
  end

  # copy just the projects, without assigned percentages
  def copy_reports_from source
    source.reports.each do |report|
      next unless report.user.active?

      dupped = report.dup
      dupped.estimated = true
      report.report_parts.each do |part|
        next if part.contract.finished?

        dupped.report_parts << ReportPart.new(contract_id: part.contract_id,
          role_id: part.role_id)
      end
      reports << dupped
    end
  end

  def base_rate
    self["base_rate"] || 175.0
  end

  def announcement
    msg = <<-EOS
      @here Hello!
      #{date.strftime("%B")}'s report is ready to be filled in! Please go to https://vizz-trackr.herokuapp.com/my-report to do it.
      If you don't have a password yet, please use the Forgot your Password feature with your Vizzuality email. :simple_smile:.
      Thank you!
    EOS
    {
      channel: Rails.env.production? ? "#announcements" : "#vizz-tracker",
      text: msg,
      icon_emoji: ":vizzuality:",
      parse: "full"
    }.to_json
  end

  def to_csv
    content = users_as_rows
    CSV.generate(headers: true, encoding: "ISO-8859-1") do |csv|
      csv << content.first.keys
      content.each do |c|
        csv << c.values
      end
    end
  end

  def users_as_rows
    content = []
    users.order(:name).each do |user|
      data = {}
      data["staff"] = user.name
      report = reports.find_by(user_id: user.id)
      Contract.where(id: report_parts.map(&:contract_id).uniq)
        .includes(:project).order(:name).each do |contract|
        percentage = report.report_parts
          .where(contract_id: contract.id)
          .sum(:percentage) || 0
        data[contract.full_name] = percentage && (percentage / 100).round(2)
      end
      data["estimated"] = report.estimated?
      content << data
    end
    content
  end

  def contracts_mean_variance_and_stdev filters
    contracts = full_reports
      .contracts_distribution(filters).first.try(:contracts)

    return {} unless contracts

    mean = contracts.inject { |sum, el| sum + el }.to_f / contracts.size

    step = contracts.inject(0) { |accum, i| accum + (i - mean)**2 }
    variance = contracts.size > 1 ? step / (contracts.size - 1).to_f : nil

    stdev = variance ? Math.sqrt(variance).try(:round, 2) : nil

    {
      contracts: contracts,
      mean: mean.round(2),
      variance: variance.try(:round, 2),
      stdev: stdev.try(:round, 2)
    }
  end

  def self.analyse filters
    result = []
    teams = Team.where(name: %w[K Rosling]).order(:name)

    ReportingPeriod.order(:date).each do |rp|
      next unless rp.full_reports.any?

      data = {rp: rp}
      teams.each do |t|
        filters_with_team = filters.merge(team_id: t.id)
        metrics = {}
        metrics[:total_contracts] = rp.full_reports
          .filtered(filters_with_team).select(:contract_id)
          .distinct.count

        metrics[:total_reporters] = rp.full_reports
          .filtered(filters_with_team).select(:user_id)
          .distinct.count

        metrics.merge!(rp.contracts_mean_variance_and_stdev(filters_with_team))

        data[t.name.to_sym] = metrics
      end
      result << data
    end
    result
  end
end

app/controllers/reporting_periods_controller.rb
class ReportingPeriodsController < ApplicationController
  before_action :set_reporting_period, only: [:show, :edit, :update, :reports,
    :announce, :destroy, :update_state]
  authorize_resource

  # GET /reporting_periods
  # GET /reporting_periods.json
  def index
    @reporting_periods = ReportingPeriod.order(date: :desc)
      .includes(:full_reports).page params[:page]
    @data = ::Api::Charts::ReportingPeriod.new(@reporting_periods)
      .reporting_periods_cost_data
  end

  # GET /reporting_periods/1
  # GET /reporting_periods/1.json
  def show
    @total_reporters = @reporting_period.full_reports
      .select(:user_id).distinct.count
    @total_project_reports = @reporting_period.total_contracts_reported
    @user_reports = @reporting_period.reports
      .includes(:user)
      .joins(:user).order("users.name ASC")
    @contract_reports = @reporting_period.full_reports
      .includes(:contract)
      .joins(contract: :project)
      .select(:contract_id,
        :contract_name,
        "sum(cost) AS cost, sum(days) AS days, projects.is_billable")
      .group(:contract_id, :contract_name, "projects.is_billable")
      .order(:contract_name)
  end

  def announce
    post_response = Slack::SlackApiHelper.post("chat.postMessage", @reporting_period.announcement)
    if post_response["ok"]
      redirect_to reporting_periods_url, notice: "Announcement successfully sent to slack!"
    else
      redirect_to reporting_periods_url, alert: "Failed to announce, please try again later."
    end
  end

  def reports
    respond_to do |format|
      format.html do
        @roles = Role.order(:name)
        @reports = @reporting_period.full_reports
          .includes(:contract, :project).order(:user_name)

        @reports = @reports.for_role(params[:role_id]) if params[:role_id].present?
      end
      format.csv do
        send_data @reporting_period.to_csv,
          type: "csv",
          filename: "report-#{@reporting_period.display_name}.csv"
      end
    end
  end

  # GET /reporting_periods/new
  def new
    @reporting_period = ReportingPeriod.new
    @reporting_periods = ReportingPeriod.order(date: :desc)
  end

  # GET /reporting_periods/1/edit
  def edit
    @reporting_periods = ReportingPeriod.order(date: :desc)
  end

  # POST /reporting_periods
  # POST /reporting_periods.json
  def create
    @reporting_period = ReportingPeriod.new(reporting_period_params)
    if params[:copy_reporting_period_id]
      source = ReportingPeriod.find(params[:copy_reporting_period_id])
      @reporting_period.copy_reports_from source
    end

    respond_to do |format|
      if @reporting_period.save
        format.html { redirect_to :reporting_periods, notice: "Reporting period was successfully created." }
        format.json { render :show, status: :created, location: @reporting_period }
      else
        format.html do
          @reporting_periods = ReportingPeriod.order(date: :desc)
          render :new
        end
        format.json { render json: @reporting_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reporting_periods/1
  # PATCH/PUT /reporting_periods/1.json
  def update
    respond_to do |format|
      if @reporting_period.update(reporting_period_params)
        format.html { redirect_to reporting_periods_path, notice: "Reporting period was successfully updated." }
        format.json { render :show, status: :ok, location: @reporting_period }
      else
        format.html { render :edit }
        format.json { render json: @reporting_period.errors, status: :unprocessable_entity }
      end
    end
  end

  def income
    @contracts = Contract.where(aasm_state: "live")
      .joins(:project).where(projects: {is_billable: true})
      .order("projects.name ASC")
    @timeframe = set_timeframe
    @monthly_incomes = MonthlyIncome
      .joins(:contract)
      .where(contracts: {id: @contracts.pluck(:id)},
        month: @timeframe)
      .order(month: :desc)
  end

  def update_state
    respond_to do |format|
      if @reporting_period.public_send("#{reporting_period_params[:aasm_state]}!")
        format.html { redirect_to reporting_periods_path, notice: "Reporting period was successfully updated." }
        format.json { render :show, status: :ok, location: @reporting_period }
      else
        format.html { render :edit }
        format.json { render json: @reporting_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reporting_periods/1
  # DELETE /reporting_periods/1.json
  def destroy
    @reporting_period.destroy
    respond_to do |format|
      format.html { redirect_to reporting_periods_url, notice: "Reporting period was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reporting_period
    @reporting_period = ReportingPeriod.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reporting_period_params
    params.require(:reporting_period).permit(:date, :base_rate, :aasm_state)
  end

  def set_timeframe
    (3.months.ago.to_date..5.months.from_now.to_date)
      .map { |d| Date.new(d.year, d.month, 1) }.uniq
  end
end

app/helpers/reporting_periods_helper.rb
module ReportingPeriodsHelper
  def event_color(state)
    case state
    when "reactivate"
      "btn-primary"
    when "terminate"
      "btn-warning"
    when "activate"
      "btn-success"
    else
      "btn-success"
    end
  end

  # returns [value, projected::boolean] or nil
  def income_val contract, month, incomes
    val = incomes.find { |m| m.contract_id == contract.id && m.month == month }&.income
    return [val, false] if val
    return [contract.linear_income, true] if contract.latest_progress_report && month > contract.latest_progress_report.date && month < contract.end_date

    nil
  end

  def reporting_period_income rperiod, contract
    return nil unless contract.budget

    income = contract.monthly_incomes.where(reporting_period_id: rperiod.id).first
    return income.income if income

    if rperiod.date < contract.end_date &&
        (!contract.latest_progress_report || contract.latest_progress_report.date > rperiod.date)
      return contract.linear_income
    end

    nil
  end
end

app/views/reporting_periods/_actions.html.erb
<% content_for :actions do
  actions = link_to('Show', reporting_period, class: 'btn btn-sm btn-outline-info')
    .concat(link_to('Detailed Reports', reports_reporting_period_path(reporting_period), class: 'btn btn-sm btn-outline-info')
    .concat(link_to('Download', reports_reporting_period_path(reporting_period, format: 'csv'), class: 'btn btn-sm btn-outline-info')))
  if can? :manage, reporting_period
    actions = actions.concat(link_to('Edit', edit_reporting_period_path(reporting_period), class: 'btn btn-sm btn-outline-primary'))
  end
  actions.concat(link_to('Back', reporting_periods_path, class: 'btn btn-sm btn-outline-secondary'))
end %>

app/views/reporting_periods/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <%= form_with(model: reporting_period, local: true) do |form| %>
          <% if reporting_period.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(reporting_period.errors.count, "error") %> prohibited this reporting_period from being saved:</h2>

              <ul>
                <% reporting_period.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="position-relative row form-group">
            <%= form.label :date, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= form.date_select :date, { discard_day: true, order: [:month, :year] }, class: "form-control" %>
            </div>
          </div>


 <!--          <div class="position-relative row form-group">
            <%#= form.label :base_rate, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <div class="input-group">
                <div class="input-group-prepend">
                  <div class="input-group-text">€</div>
                </div>
                <%#= form.text_field :base_rate, class: 'form-control' %>
              </div>
            </div>
          </div> -->

          <% if reporting_period.new_record? %>
            <div class="position-relative row form-group">
              <%= label_tag :copy_reporting_period_id, 'Copy Reports From', class: 'col-sm-2 col-form-label' %>
              <div class="col-sm-10">
                <%= select_tag :copy_reporting_period_id,
                  options_from_collection_for_select(@reporting_periods, :id, :display_name),
                  include_blank: true, class: "form-control" %>
                <small class="form-text text-muted">
                  This will only copy the contracts allocations without percentages or costs. The goal
                  is to make it easier for people to fill in their new reports, as part of their projects will
                  be there already.
                </small>
              </div>
            </div>
          <% end %>

          <div class="position-relative row form-group">
            <div class="col-sm-10 offset-sm-2">
              <%= form.submit "Submit", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reporting_periods/edit.html.erb
<% content_for :title, "Editing Reporting Period" %>
<%= render 'actions', reporting_period: @reporting_period %>

<%= render 'form', reporting_period: @reporting_period %>

app/views/reporting_periods/income.html.erb
<% content_for :title, "Income from live projects period #{@timeframe.first.strftime("%B %Y")} - #{@timeframe.last.strftime("%B %Y")}" %>
<% if can? :create, ReportingPeriod %>
  <% content_for :actions do
      link_to('Back', reporting_periods_path, class: 'btn btn-sm btn-outline-info')
    end
  %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th>Contract</th>
                <th class="currency-col">Budget</th>
                <th class="currency-col">Costs to date</th>
                <th class="currency-col">Income to date</th>
                <th>Progress</th>
                <% @timeframe.each do |month| %>
                  <th class='currency-col <%= "border border-primary" if month == Time.now.beginning_of_month %>' scope="col">
                    <%= month.strftime('%B \'%y') %>
                  </th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% total = Hash.new(0) %>
              <% @contracts.each do |contract| %>
                <% next unless @monthly_incomes.find{|m| m.contract_id == contract.id} %>
                <tr>
                  <td class="text-col"><%= link_to contract.full_name, contract %></td>
                  <td><%= number_to_currency(contract.budget) %></td>
                  <td><%= number_to_currency(contract.total_burn) %></td>
                  <td><%= number_to_currency(contract.income_to_date) %></td>
                  <td><%= "#{contract.latest_progress_report.percentage}%" if contract.latest_progress_report %></td>
                  <% @timeframe.each do |month| %>
                    <% val, projected = income_val contract, month, @monthly_incomes %>
                    <td class="<%= projected ? 'text-info' : 'text-success' %>">
                      <% if val %>
                        <% total[month] += val %>
                        <%= number_to_currency(val) %>
                      <% end %>
                    </td>
                  <% end %>
                </tr>
              <% end %>
              <tr>
                <th colspan=5>Total</th>
                <% @timeframe.each do |month| %>
                  <td><%= number_to_currency(total[month]) %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
          <p>
            <span class="text-success">Income based on progress report.</span><br />
            <span class="text-info">Income calculated linearly from remaining project timeframe and budget.</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reporting_periods/index.html.erb
<% content_for :title, "Reporting Periods" %>
<% if can? :create, ReportingPeriod %>
  <% content_for :actions, link_to('New Reporting Period', new_reporting_period_path, class: 'btn btn-sm btn-outline-primary') %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <h5 class="card-title">Cost in Projects</h5>
        <div class="widget-chart-wrapper widget-chart-wrapper-lg opacity-10 m-0">
          <%= line_chart @data, prefix: '€', thousands: "," %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <div class="table-responsive">
          <%= page_entries_info @reporting_periods %>
          <table class="table table-sm">
            <thead>
              <tr>
                <th>Period</th>
                <th>Final Reports</th>
                <th>Estimated Reports</th>
                <th>Common actions</th>
                <th>Change status</th>
              </tr>
            </thead>

            <tbody>
              <% @reporting_periods.each do |reporting_period| %>
                <tr>
                  <td><%= link_to reporting_period.display_name, reporting_period %></td>
                  <td><%= reporting_period.reports.where(estimated: false).count %></td>
                  <td><%= reporting_period.reports.where(estimated: true).count %></td>

                  <td>
                    <div class="btn-group mr-2">
                      <% if reporting_period.active? && can?(:manage, ReportingPeriod) %>
                        <%= link_to 'Announce!', announce_reporting_period_path(reporting_period), class: 'btn btn-success btn-sm' %>
                      <% end %>
                      <%= link_to 'Download', reports_reporting_period_path(reporting_period, format: 'csv'), class: "btn btn-primary btn-sm" %>
                      <%#= link_to 'New report', new_reporting_period_report_path(reporting_period), class: "btn btn-primary" %>
                      <% if can? :manage, ReportingPeriod %>
                        <%= link_to 'Bulk import', new_reporting_period_bulk_import_path(reporting_period), class: "btn btn-primary btn-sm" %>
                        <%= link_to 'Edit', edit_reporting_period_path(reporting_period), class: "btn btn-primary btn-sm" %>
                        <%= link_to 'Destroy', reporting_period, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
                      <% end %>
                    </div>
                  </td>
                  <td>
                    <% if can? :manage, ReportingPeriod %>
                      <%= form_with(url: reporting_period_update_state_path(reporting_period), model: reporting_period, method: :patch, local: true) do |form| %>
                        <%= form.hidden_field(:aasm_state, value: reporting_period.next_event) %>
                        <%= form.submit reporting_period.next_event, class: "btn btn-sm #{event_color(reporting_period.next_event)}" %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @reporting_periods %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reporting_periods/new.html.erb
<% content_for :title, "New Reporting Period" %>
<% content_for :actions,
  link_to('Back', reporting_periods_path, class: 'btn btn-sm btn-outline-secondary') %>

<%= render 'form', reporting_period: @reporting_period %>

app/views/reporting_periods/reports.html.erb
<% content_for :title, "#{@reporting_period.display_name} - Detailed Reports" %>
<%= render 'actions', reporting_period: @reporting_period %>

<%= form_with(url: reports_reporting_period_path(@reporting_period), method: :get, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :role_id %>
    <%= form.select :role_id, options_from_collection_for_select(@roles, :id, :name, selected: params[:role_id]), { prompt: true }, class: "form-control", onchange: 'this.form.submit();' %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <h5 class="card-title">Reports</h5>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>User</th>
                <th>Team</th>
                <th>Functional Area</th>
                <th>Contract</th>
                <th>Percentage</th>
                <th>Days</th>
                <th>Cost</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @reports.each do |report| %>
                <tr>
                  <td><%= link_to report.user_name, report.user %></td>
                  <td><%= report.team_name %></td>
                  <td><%= report.role_name %></td>
                  <td><%= link_to report.contract_full_name, report.contract %></td>
                  <td><%= report.percentage %>%</td>
                  <td><%= report.days %></td>
                  <td><%= number_to_currency(report.cost)  %></td>
                  <td>
                    <% if can? :edit, report.report %>
                      <%= link_to 'Edit', edit_report_path(report.report_id) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reporting_periods/show.html.erb
<% content_for :title, "Reporting Period - #{@reporting_period.display_name}" %>
<%= render 'actions', reporting_period: @reporting_period %>

<% if @reporting_period.report_parts.any? %>
  <div class="row">
    <div class="col-md-6 col-xl-4">
      <div class="card mb-3 widget-content bg-night-sky">
        <div class="widget-content-wrapper text-white">
          <div class="widget-content-left">
            <div class="widget-heading">Reporters</div>
            <div class="widget-subheading">How many members of staff filled a report this period.</div>
          </div>
          <div class="widget-content-right">
            <div class="widget-numbers text-white"><span><%= @total_reporters %></span></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xl-4">
      <div class="card mb-3 widget-content bg-slick-carbon">
        <div class="widget-content-wrapper text-white">
          <div class="widget-content-left">
            <div class="widget-heading">Projects</div>
            <div class="widget-subheading">Number of projects reported in this period.</div>
          </div>
          <div class="widget-content-right">
            <div class="widget-numbers text-white"><span><%= @total_project_reports %></span></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xl-4">
      <div class="card mb-3 widget-content bg-grow-early">
        <div class="widget-content-wrapper text-white">
          <div class="widget-content-left">
            <div class="widget-heading">Avg Project per Person</div>
            <div class="widget-subheading">Average number of projects reported.</div>
          </div>
          <div class="widget-content-right">
            <div class="widget-numbers text-white">
              <span>
                <%=  number_with_precision(@reporting_period.full_reports.count.to_f / @total_reporters, precision: 2.0) %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <h5 class="card-title">Contracts breakdown</h5>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>Contract</th>
                <th>Cost/Time Reported</th>
                <th>Monthly Income</th>
              </tr>
            </thead>
            <tbody>
              <% @contract_reports.each do |report| %>
                <tr>
                  <td><%= link_to report.contract_name, contract_path(report.contract_id) %></td>
                  <td><%= report.is_billable? ? number_to_currency(report.cost) : pluralize(report.days&.round(2), 'day') %></td>
                  <td>
                    <% if report.is_billable? %>
                      <% val = reporting_period_income(@reporting_period, report.contract) %>
                      <%= number_to_currency(val) if val %></td>
                    <% else %>
                      -
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <h5 class="card-title">Staff breakdown</h5>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>User</th>
                <th>Percentage reported</th>
                <th># Contracts</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @user_reports.each do |report| %>
                <tr class="<%= "table-warning" if report.estimated? %>">
                  <td><%= link_to report.user&.name, report.user %></td>
                  <td><%= report.report_parts.sum(:percentage) %></td>
                  <td><%= report.report_parts.count %></td>
                  <td>
                    <% if can? :edit, report %>
                      <%= link_to 'Edit', edit_report_path(report) %>
                    <% end %>
                    <% if can? :destroy, report %>
                      <%= link_to 'Remove report', report, method: :delete,
                        data: { confirm: 'Are you sure you want to remove this report?' } %>
                    <% end %>
                    <% if report.estimated? and can? :manage, report %>
                      <%= link_to 'Send Slack notification', slack_send_notification_path(report.reporting_period_id, report.user_id) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>